### ISSUE TITLE
Work with polygons

### ISSUE THREAD

**Issue by mma-amini** [map-ir/mapir-flutter-map-sdk#5]
Hello there!

How can use polygon in map?

**Comment by Mr-Alirezaa** [comment]
Hi @mma-amini ,
You can not draw closed shapes (except for circle) on the map. But there is an example available that shows [how to draw polylines. check it out on our support website](https://support.map.ir/developers/flutter/1-0-2/examples/polyline/).
You can also clone the project, build and run the example application to see how polylines work. Source code is located at `example > lib`.
You can use the example to draw a _somehow_ closed polyline (a polygon) which may fulfill the purpose. Or you can use   the example that demonstrates how to draw a circle.
